-- USERS TABLE
CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(50)  NOT NULL UNIQUE,
    password           VARCHAR(255) NOT NULL,
    role               VARCHAR(20)  NOT NULL,
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP,
);

-- CONTENTS TABLE
CREATE TABLE contents
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(100) NOT NULL,
    description        CLOB,
    view_count         BIGINT       NOT NULL DEFAULT 0,
    created_by         VARCHAR(50) NOT NULL,
    created_date       TIMESTAMP,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP,

    CONSTRAINT fk_contents_created_user
        FOREIGN KEY (created_by) REFERENCES users (id),

    CONSTRAINT fk_contents_modified_user
        FOREIGN KEY (last_modified_by) REFERENCES users (id)
);